### ISSUE TITLE
Unable to have a required Media Picker field

### ISSUE THREAD

**Issue by tomfulton** [kgiszewski/Archetype#132]
If you have a Media Picker field on your Archetype and set it to Required, Umbraco lets you save the page without selecting any media.

Presumably the media picker has 0 as it's default value, and Archetype's validation looks for null/empty/etc.  This is similar to what we're discussing in #89 with checkboxes.

Unsure what the proper fix is here since we don't know what "empty" really means to every given PropertyEditor.  May need to dig in and see how Umbraco handles this, or worst case, start adding checks for specific types...

**Comment by kjac** [comment]
Yeah.. this works.
