### ISSUE TITLE
Support Virtual Directories

### ISSUE THREAD

**Issue by tomfulton** [kgiszewski/Archetype#156]
When running an Umbraco install from a Virtual Directory, there's a few issues with Archetype.

Some of these will require updates to the core, but just using this issue to document everything we need in order to make this happen:
- [ ] Unable to find view  ([PR submitted to core](https://github.com/umbraco/Umbraco-CMS/pull/419) for [U4-5128](http://issues.umbraco.org/issue/U4-5128))
- [ ] Unable to find CSS - [U4-5127](http://issues.umbraco.org/issue/U4-5127) reported to core
  
  _Note - we could probably mitigate the CSS issue by loading the CSS via an attribute instead of [doing it manually](https://github.com/imulus/Archetype/blob/master/app/controllers/controller.js#L279).  Any reason we want to do it manually?_
- [ ] Unable to find `ArchetypeApi` endpoint as it looks at the root (/).  Probably should use Umbraco's methods to dynamically determine this location, which may fix the issue.

**Comment by djomen** [comment]
Hi,

We are experiencing an issue with Archetype and VD's

We have installed via nuget and deployed the archetype as part of the deployment but it the VD is ignored for archetype.js  

It was causing major issues with even trying to log into the backand and was cauing umbraco to just loop.

The temp workaround was to put the app plugins archetype folder in the root and all the issues went away.

Is there a way to fix this properly as i can see the plugins folder getting removed with the deployment of the root app by accident or something.

Cheers,
Damian

**Comment by djomen** [comment]
Hi,

We had further errors with this workaround with the plugin being in the directory outside the VD...

We ended up getting errors with the path when clicking on a node with an archetype because of the rooted urls in archetype.js GET requests etc to the backoffice.

So i had to remove the root - for example:

 $http.get("/umbraco/backoffice/ArchetypeApi/ArchetypeDataType/GetAll

to 

 $http.get("backoffice/ArchetypeApi/ArchetypeDataType/GetAll

It now works ok but obviously aint ideal because the archetype folder is outside the apps VD.

A way to fix in the top level path error would be better.

Cheers
Damian

**Comment by kgiszewski** [comment]
Do we know if Umbraco has a helper for Angular to find the root?

**Comment by djomen** [comment]
I can say that i dont know - i've not done enough angular. I can have a poke around though. Per could probably answer that rather quickly. Ill drop him a tweet.

**Comment by djomen** [comment]
I know there is an app setting for the umbraco path which is ~/umbraco so if that has been exposed as a helper then as you say - thats what you could use.

**Comment by kgiszewski** [comment]
If you find it, I can fix it or you can submit a PR.  Thanks for the detective work :+1:

**Comment by djomen** [comment]
Per says there is a base href on the page that outputs the VDir and to always use relative paths.  I had seen that but wasnt sure how to use it! Just read up on it and it should do the job perfectly.

 <base href="/umbraco/" />

So just make all links to source files and api calls relative.

**Comment by djomen** [comment]
Let me know if you want me to give any fix a test. 

Id do a PR but dont know the codebase enough with the time ive got to get my head around it.  I could do the js file but im not sure where archetype gets injected into the umbraco backend?

**Comment by kgiszewski** [comment]
AFAIK, this isn't an issue any longer. Please comment if contrary.
