### ISSUE TITLE
Update validation keys to match new property aliases

### ISSUE THREAD

**Issue by tomfulton** [kgiszewski/Archetype#163]
We've added some (pending) code in #157 that changes the way we're generating property aliases to make them more unique.

I noticed the validation is also [keying off property aliases](https://github.com/imulus/Archetype/blob/master/app/directives/archetypeproperty.js#L131), so we should probably update that to use the new format as well.  Not sure if it might run into the same issues with nested archetypes' property aliases not being totally unique in some cases.

I think we should drop this [alias](https://github.com/imulus/Archetype/blob/fix/unique-aliases/app/directives/archetypeproperty.js#L179) parameter altogether in favor of `propertyAlias` which is the new unique format.

I'm curious if there might be other areas as well and what's involved with updating them to use the new format, [for example](https://github.com/imulus/Archetype/blob/master/app/directives/archetypeproperty.js#L174) and a few other places in the directive.  Holding until I or someone else has time to look at this & test :)
# tiredbraindump

**Comment by kjac** [comment]
This issue was fixed with #174
