### ISSUE TITLE
Archetype doesn't work when switching from other datatype

### ISSUE THREAD

**Issue by jbreuer** [kgiszewski/Archetype#197]
If you have a textbox with a value and you change the type from textbox to Archetype on the documenttype it won't work on nodes that already had a value in the textbox. Same goes for other previous datatypes. I know that those values can't be converted to Archetype anyway, but it should probably just show an empty Archetype on the node instead.

Previous property with value.
![a1](https://cloud.githubusercontent.com/assets/5444597/3853966/36fa3688-1ecf-11e4-8db9-7659d4cddc17.jpg)
Previous property without value.
![a2](https://cloud.githubusercontent.com/assets/5444597/3853968/3d158202-1ecf-11e4-8957-42c36d67ff2b.jpg)

**Comment by kgiszewski** [comment]
Closing this. We're not likely to directly address JSON corruption due to data type switching\renaming.
