### ISSUE TITLE
Conflict with Umbraco's tabs hightlighting

### ISSUE THREAD

**Issue by bjarnef** [kgiszewski/Archetype#201]
I just noticed a conflict with hightlighting of the tabs, when using Archetype as datatype. On the top node I had a property using Archetype and this node also had a child node (HomePage node) where I use a property with Archetype.
But when I save or publish the node from a different tab than the first node, the first tab is highlighted. When I change the datatypes for these two properties on each node to e.g. a textstring, this isn't a issue. I am using Umbraco 7.1.4 and Archetype 1.4.1-beta.
I also tried a clean 7.1.4 install with the txt starterkit and without Archetype, where it doesn't seems to be an issue.

I had created this issue here first http://issues.umbraco.org/issue/U4-5347 (check out the short video of the issue), but I think it's related to Archetype.

/Bjarne

**Comment by kjac** [comment]
This isn't happening anymore, yay :)
