### ISSUE TITLE
Archetype not saving Macro Container property (and RTE doesnt display macro)

### ISSUE THREAD

**Issue by BenFidge** [kgiszewski/Archetype#208]
Hi 

I've created an archetype fieldset that consists of a single Macro Container property. When I save my document, the selected macro is not being saved to the database.

If I use a RTE as the property type and use its Embed Macro command, this IS saved to db BUT the RTE doest render the macro (see pic). IF you click the view html source command in the RTE you can see the macro tags. 

This is whats saved in DB:

{"fieldsets":[{"properties":[{"alias":"rightColumn","value":"1054"},{"alias":"leftColum","value":""}],"alias":"richTextWidget","disabled":false}]}

The value 1054 is the contentNodeId value in the cmsPropertyData table.

My Archetype datatype is configured as so:

{"showAdvancedOptions":true,"startWithAddButton":true,"hideFieldsetToolbar":false,"enableMultipleFieldsets":true,"hideFieldsetControls":false,"hidePropertyLabel":false,"maxFieldsets":null,"enableCollapsing":true,"enableDisabling":true,"enableDeepDatatypeRequests":true,"fieldsets":[{"alias":"richTextWidget","remove":false,"collapse":true,"labelTemplate":"{{richTextWidget}}","icon":"icon-layout","label":"Rich Text + Widget","properties":[{"alias":"leftColum","remove":false,"collapse":true,"label":"LeftColum","helpText":"","dataTypeGuid":"ca90c950-0aff-4e72-b976-a30b1ac57dad","value":"","aliasIsDirty":true},{"alias":"rightColumn","remove":false,"collapse":true,"label":"Right Column","helpText":"","dataTypeGuid":"d1c603cf-7380-482c-83c3-1b824a36a657","value":"","aliasIsDirty":true}],"aliasIsDirty":true,"$$hashKey":"0MV"},{"alias":"singleWidget","remove":false,"collapse":true,"labelTemplate":"{{widget}}","icon":"icon-layout","label":"Single Widget","properties":[{"alias":"widget","remove":false,"collapse":true,"label":"Widget","helpText":"","dataTypeGuid":"d1c603cf-7380-482c-83c3-1b824a36a657","value":"","required":true,"aliasIsDirty":true}],"aliasIsDirty":true,"$$hashKey":"0MW"}]}

![capture](https://cloud.githubusercontent.com/assets/8555829/4043481/cb373e7c-2d11-11e4-97e0-9cb568ea5f21.PNG)

**Comment by kjac** [comment]
As if by magic, macros in RTE's work with Archetype now. No idea when or how that was fixed 🤔 but it works.
