### ISSUE TITLE
Properties Contaminating Archetype Config

### ISSUE THREAD

**Issue by Nicholas-Westby** [kgiszewski/Archetype#219]
The properties "$$hashkey" and "aliasIsDirty" are on the config, but they appear to serve no purpose for the config. Probably best to remove these as they will bloat the config and may (or may not) cause issues later (e.g., if they interfere with Angular when the config is used elsewhere).

More details here (including some example JSON): http://our.umbraco.org/projects/backoffice-extensions/archetype/sound-off!/56014-Angular-Properties-Polluting-Archetype-Config

Here's a screenshot of some of the properties on the config:
![properties](https://cloud.githubusercontent.com/assets/5933222/4121363/ab1997d0-32ba-11e4-9c9b-f064aefd9876.png)

**Comment by Nicholas-Westby** [comment]
Yeah, that's about how I handled it in Formulate: https://github.com/rhythmagency/formulate/blob/08eef0bbee2a54a3923a204bf8b11c30caa4b4b8/src/formulate.app/Directives/formDesigner/designer.js#L172

```
fields: angular.fromJson(angular.toJson(fields)),
handlers: angular.fromJson(angular.toJson(handlers))
```

**Comment by kgiszewski** [comment]
Closing for now. It's more annoyance than hindrance.
