### ISSUE TITLE
Pages with alot of Archetype data, if you save fast, it doesn't save all the field

### ISSUE THREAD

**Issue by GoodGuyShinsuke** [kgiszewski/Archetype#234]
Hi guys,

Thank you soo much for creating this addon. Love this product.

However I have this 1 concern,

I have this page containing alot of Archetype data, it all works fine. But today my client rang us and said we loosing some contents. So i start doing some internal testing.

We found that the page with alot of Archetype contents takes some time to load, and when you save the data before all the content's been populated by angular js, it looses those data.

Solution was quite simple, ask client to wait till all the contents are loaded.

However if its possible, i thought it might be good idea to have some kind of loading image and disable a page till all the archetype data are filled.

I'm using

Umbraco 7.1.8

Archetype 1.5.0-beta

Thank you

Shinsuke

**Comment by kgiszewski** [comment]
Adding a performance enhancement soon Ref=> #253

**Comment by kjac** [comment]
We won't get any closer to solving this than what we've got from the various lazy loading improvements. If anyone is still experiencing issues with this, please add comments to this issue, but I'm closing it for now.
