### ISSUE TITLE
Adding support for minimum number of Fieldsets

### ISSUE THREAD

**Issue by SanderBlokzijl** [kgiszewski/Archetype#249]
Next to the option of the max number of fieldsets it would be awesome to have a minimum also. Great to force a specific number of fieldsets when the design desires this.

**Comment by bradleyflood** [comment]
+1

**Comment by alnicholl77** [comment]
+1

**Comment by kgiszewski** [comment]
I may have recently had the need for this as well.

So if I get a chance I'll add this functionality.

I'm thinking besides just raw number of fieldsets, the type might be considered as well in the use-case of multiple fieldsets.

**Comment by geoffbeaumont** [comment]
+1

**Comment by dconlisk** [comment]
+1

**Comment by kennyburns1967** [comment]
+1

**Comment by owenblacker** [comment]
+1

**Comment by Draga** [comment]
+1

**Comment by argentini** [comment]
+1

**Comment by argentini** [comment]
It would be great to just add the minimum number first to get it in there quickly, and then evolve it to support deeper inspection. Just sayin!

**Comment by kjac** [comment]
@argentini (and everyone else) I've got a working feature branch for this. It validates the number of enabled fieldsets against a configurable minimum number of fieldsets. When we get around to creating a new release, this will probably go in there.

**Comment by kgiszewski** [comment]
Nice 😁

**Comment by kelvinschutz** [comment]
@kjac Is the feature branch on remote by chance? I ran into a need for minimum fieldsets lately and was thinking of having a go at it. I looked through your fork and here, but didn't see any branches with recent work on them for minimum fieldsets.

**Comment by kjac** [comment]
@kelvinschutz I have it in my local repo. I'm on vacation at the moment... will submit a PR as soon as I can, probably next week.

**Comment by kelvinschutz** [comment]
@kjac That's awesome! Let me know if there is any way I can assist :)

**Comment by kjac** [comment]
@kelvinschutz I'm going to play around with Archetype the next few days, it should be ready shortly.

Here's a sneak preview:

![archetype-min-fieldsets](https://user-images.githubusercontent.com/7405322/29108513-96c025fc-7cdf-11e7-985c-adc99ad8e41c.gif)

/cc @kgiszewski

**Comment by SanderBlokzijl** [comment]
@kjac Epic! Looks already awesome 👍

**Comment by kelvinschutz** [comment]
@kjac This is excellent!

**Comment by kjac** [comment]
Added in v1.15.1
