### ISSUE TITLE
Template title and the 'Url picker' strange behaviour

### ISSUE THREAD

**Issue by MrMattTaylor** [kgiszewski/Archetype#250]
I've created a data type by configuring an Archetype control to contain a couple of controls and a 'Url picker'.

![1](https://cloud.githubusercontent.com/assets/6153443/5817915/ac5c0a36-a0a8-11e4-896a-766fd8c34bc5.jpg)

Without thinking too hard I set the Template Label to {{title}} and observed some strange behaviour.

It seems that when I create the content the label of the first fieldset is set to the value of the 'title' property of the Url picker.

That's actually what I wanted although I suspect it is by complete chance.

The problem is that the label of any subsequent fieldsets is left blank, as shown here.

![2](https://cloud.githubusercontent.com/assets/6153443/5818034/a6bd5e08-a0a9-11e4-9a97-78add028c2e0.jpg)

You cannot see the contents of the last two fieldsets but I assure you they are populated.

Regards, Matt

**Comment by kgiszewski** [comment]
Wow, I'm surprised it even worked at all :)  The label template takes either `{{propertyAlias}}` or a function.  The fact that the property of a nested datatype working is strange.

**Comment by MrMattTaylor** [comment]
I know. LOL

**Comment by kjac** [comment]
The URL Picker isn't supported out of the box. I recommend using the [Multi Url Picker](https://our.umbraco.org/projects/backoffice-extensions/multi-url-picker/) instead, it works with label templates.
