### ISSUE TITLE
JSON string as a property value is not rendered correctly

### ISSUE THREAD

**Issue by dbardi** [kgiszewski/Archetype#265]
Using a multi-textstring property doesn't retrieve JSON data correctly.

If I enter a json string as a value in the UI and save, it appears ok.
When I return to the doctype and view the property, the value is not retrieved as a string, but instead as [object Object].

![screenshot 2015-04-22 02 06 39](https://cloud.githubusercontent.com/assets/5032251/7269824/4e17ab5e-e894-11e4-9dc1-93c69c3f7bde.png)

**Comment by kgiszewski** [comment]
Any idea if a non-Archetype multiline textfield has the same issue?

You may need to create a custom property editor that doesn't evaluate the input as JSON (just a first guess).

**Comment by kjac** [comment]
This is indeed a problem with the core property editor.

If anyone encounters this issue, try prefixing your JSON with a symbol, e.g. "#[{title:"hello"},{title:"world"}]" instead of "[{title:"hello"},{title:"world"}]".
