### ISSUE TITLE
Localizing Archetype Properties' Labels and Widgets' Names

### ISSUE THREAD

**Issue by iahdevelop** [kgiszewski/Archetype#290]
Hello

I have a Multilanguage site, And i need the name of widgets to be compatible with the language of the user. Does any way to do that with Archetype? I tried to put # and the property dectionary key, but it didnt work.

**Comment by kgiszewski** [comment]
Sorry, at present Archetype does not handle dictionary items.

I've marked this as a feature request. We currently do not have plans to implement at this time but would welcome a pull-request for such a feature.

**Comment by kgiszewski** [comment]
Related to #239 it seems. I'm gonna keep this open as this might get some love (one day).
