### ISSUE TITLE
Old fieldset aliases not getting cleaned out

### ISSUE THREAD

**Issue by kgiszewski** [kgiszewski/Archetype#304]
Somehow this was left in one of my Archetypes and it could have been via rearrange, renaming, removing datatypes, etc.

```
{"alias":"navigationHashTag","value":"foo","propertyEditorAlias":null,"dataTypeId":0,"dataTypeGuid":null,"editorState":null,"hostContentType":null},
```

This will cause issues with things that depend on the `dataTypeGuid` not being null.

Perhaps we need to clean out invalid data on save.

**Comment by kgiszewski** [comment]
Symptoms of this may include a property value converter failing for no apparent reason.

**Comment by kgiszewski** [comment]
Appears this should have been fixed by detecting `propertyEditorAlias` as `null` instead  of `datatypeguid`.

Report of creating Archetype in code failing now.

**Comment by kgiszewski** [comment]
Hmmm, testing for empty `propertyEditorAlias` kills the entire fieldset :(

**Comment by kgiszewski** [comment]
Rolling back this fix for now for v.1.12.1

**Comment by kjac** [comment]
@kgiszewski I haven't heard any reports on this problem in the past... well, year. Any idea if it's still relevant?

**Comment by kgiszewski** [comment]
Let's close it.
