### ISSUE TITLE
Validation error when saving Document Type based on ArcheType within ArchType

### ISSUE THREAD

**Issue by JLarue** [kgiszewski/Archetype#317]
I have an ArcheType that has one string property which is not set to required and has default set.on it.
I am able to add this to a document type and save with out issue.

I created a second ArcheType that has two properties, one a string, not set to required has defaut value set on it.  The second property is the first ArcheType described above. 

When add the second AcheType to Doc Type and try to press save, I get a validation error.  It doesn't tell me why its not valid, just won't let me save it out.  
I am running on 7.4

**Comment by kgiszewski** [comment]
@JLarue, thanks for the bug report. I assume the 'required' is the Archetype configuration required and not the 'mandatory' box on the document type.

Since you are using nested Archetypes, there may be an issue with the logic. At some point I'll try to replicate this but it will also be some time before I'm able to test against 7.4.

**Comment by JLarue** [comment]
Correct, it is the 'required' within Archetype configuration.

**Comment by kipusoep** [comment]
I'm running into this as well, but with a more simple situation.
One Archetype with one or more fields required, but the property for the Archetype editor is not mandatory.
This will give you a validation error when you didn't enter anything into the Archetype editor.

**Comment by kipusoep** [comment]
Quick fix: enable 'Start With Add Button?'

**Comment by kjac** [comment]
The fix suggested by @kipusoep is indeed the only way around this scenario. You can't have a fieldset with mandatory properties *not* report validation errors, no matter if the Archetype property itself isn't mandatory on the document type.
