### ISSUE TITLE
Required properties can by bypassed

### ISSUE THREAD

**Issue by webmonger** [kgiszewski/Archetype#325]
Create an archetype DataType with 1 or more required fields, add it to your document type

Create your document in the content area, then press the add button twice to create 2 items in your archetype, press Save and Publish - you'll receive the required fields error.

Input content in to one of your field sets and leave the other one hidden, press save and publish and it'll succeed when the other values are empty.

**Comment by kgiszewski** [comment]
Thanks for the report.

This is likely due to an oversight with #301 (just guessing at the moment).

Since the fieldset is never rendered when closed, the validation doesn't trigger.

Possible solution would be to disallow adding additional fieldsets if validation fails.

**Comment by webmonger** [comment]
Unfortunately I don't think that would fix the issue as you can add 3 items and fill them out properly and then retrospectively invalidate them.

It really needs to be some value held elsewhere that maintains the validation state and reports when items are hidden.

**Comment by kgiszewski** [comment]
Hmmm.

That's the rub then. The increase in performance is due to the fact that each Archetype isn't rendered until opened. 

Validation is super tricky with Archetype and we'd likely have to re-invent the wheel to overcome this. 

Another approach might be to validate the fieldset if attempting to move away from it/close it/add another/etc.

**Comment by webmonger** [comment]
Yes I think that's a much better option however then you'll need to hook validation up to anything that causes fieldsets to be hidden like the add button(Though this might be easier than it sounds).

It will also become an issue on nested archetype types as the validation will need to be recursive.

Sorry don't sound like I'm helping much really

**Comment by kgiszewski** [comment]
It's all good. The bad part is I don't think we have a plan to put into action just yet so as such I think we'll have to all wait for a clearer path to fix.

**Comment by kjac** [comment]
@webmonger I'm pretty sure that #351 fixes this. I'll close the issue, feel free to reopen it if you're still experiencing the problem.
