### ISSUE TITLE
Feature request: Max fieldset to count only enabled fieldsets

### ISSUE THREAD

**Issue by seanhak** [kgiszewski/Archetype#333]
It would be nice if there was an extra option that disabled number of active fieldsets.
This would allow editor to add unlimited sets, but can only enable X amount.

This is useful for adding temporary campaigns and still have a max item validation in the CMS.

**Comment by kgiszewski** [comment]
Leaving this open for now, but would like to see if we can get additional voters before we spend some time on this.
