### ISSUE TITLE
Add a spinner when expanding fieldsets

### ISSUE THREAD

**Issue by bjarnef** [kgiszewski/Archetype#336]
I have upgraded a site from Umbraco 7.2.4 to 7.4.1

Furthermore it have upgraded Archetype from v. 1.7.5 to 1.12.2

Before it looked like this:

![image](https://cloud.githubusercontent.com/assets/2919859/13490320/283558be-e12c-11e5-97e7-5f9050d4652a.png)

Now I don't see any property fields:

![image](https://cloud.githubusercontent.com/assets/2919859/13490383/78be4566-e12c-11e5-967e-a54bb87d11da.png)

**Comment by bjarnef** [comment]
If I turn set ```debug=false``` in web.config it seems to work better.

![image](https://cloud.githubusercontent.com/assets/2919859/13490625/17c73040-e12e-11e5-972e-3e5a3c4f5311.png)

**Comment by bjarnef** [comment]
I have reverted back to v. 1.7.5 as it seems to work better.

![image](https://cloud.githubusercontent.com/assets/2919859/13490919/8570eb3a-e12f-11e5-8a4a-7e3f970884ac.png)

**Comment by kgiszewski** [comment]
@bjarnef, thank you for reporting. That's unsettling of course. I suspect that it might be a simple case of caching, but the latest version of the core I'm running Archetype with is 7.3.8.

I'm curious if any UaaS users are having issues.

**Comment by bjarnef** [comment]
@kgiszewski okay, I have tested with 1.12.2 on a test server (staging) and it seems to work much better than when running locally... during upgrade on local I forget to increase clientDependency version number, but I did that before running the upgrade installer on staging site.. so I am not sure if that makes a different.

It seems to works okay there - just sometimes when clicking the fieldset header after init the node view it might seems that nothing happens (but I think it happens because it takes ~1 second to init the properties)...
Maybe Archetype can have some kind of a preloader until it is ready - similar to that Richtext editor has a loading message until TinyMCE editor is ready.

**Comment by kjac** [comment]
@bjarnef We could add a spinner when expanding the fieldsets, but how big is the problem? I mean... how long does it take before the first property gets displayed? In my tests it's pretty much instantaneous, but maybe your server is under more stress and doesn't return the property editors to the fieldset as fast as one might like.

**Comment by bjarnef** [comment]
@kjac we had some issues with the site after upgrading from Umbraco 7.2.4 to 7.4.1, but somehow it seems that ModelsBuilder wrote a lot of logs entries: http://issues.umbraco.org/issue/U4-8182

The site was upgraded manually and merging the config files, so ModelsBuilder was enabled, but after we disabled ModelsBuilder the site was running a lot faster and not using same among of CPU.

After that I didn't really had issues with Archetype even though it might take 0,5-1 second to init. But a preloader might be useful like when expanding tree nodes.

There are the built-in .umb-loader + .umb-loader-wrapper.

**Comment by kjac** [comment]
After digging into this, it's not any kind of easy to fix. There is no consistent way of telling if a property editor has loaded or not. So I'm going to have to close this. If anyone comes up with a solution, by all means submit a PR.
