### ISSUE TITLE
Feature request: Limit fieldset access to groups

### ISSUE THREAD

**Issue by kjac** [kgiszewski/Archetype#341]
#334 (and #340) introduced publish and unpublish dates. Seems to me the obvious next step is to support group access per fieldset?

![archetype-groups-1](https://cloud.githubusercontent.com/assets/7405322/13985093/dbd3823c-f0fa-11e5-9dfb-b973b3fae27c.png)

It should be pretty straight forward to build this on top of #340. As you can see in the screenshot I've sorta got a semi functional prototype up and running.

**Comment by kgiszewski** [comment]
Interesting concept. We toyed with a similar thing in the early days.

I have a few questions naturally :)

The `Allowed Groups` is on the editor side of things and implies that it is setup at the content level as opposed to the config side which would mean it affects all instances of the data type. Is the advantage intended to customize at the content level?

If so, how do we restrict access to this setting to non-admins (if that is your intent)?

**Comment by kjac** [comment]
@kgiszewski It's indeed intended to customize at content level. Consider it the fieldset equivalent of the built-in "Public access" on pages. Therefore I don't see any need to restrict access to this setting - it's an editor feature, it should be freely available for the editors.

Obviously it would be enabled explicitly on the config side, just like publishing.

**Comment by kgiszewski** [comment]
Fair enough. I'm just trying to foresee a future request to restrict these.

Also, if enabled in conjunction with 'Start with add', would there be a situation where nothing could be added since the ACL is blank? Assuming you'd have to handle that edge case.

One last thing, if fieldset type `x`, `y` & `z` are saved into content. Then `x` gets removed from the `allowed`. Do we keep it or remove it?

**Comment by kjac** [comment]
Uhm... not sure I follow? The feature is not about fieldset groups, it's about member groups. So per fieldset I as an editor can limit the access to specific fieldsets to certain member groups.

**Comment by kgiszewski** [comment]
![homer-simpson-wingnuts-doh](https://cloud.githubusercontent.com/assets/4653907/13987436/e5206e76-f0dd-11e5-9f22-79613ca3236c.gif)

Ok, forget what I said :)

**Comment by kjac** [comment]
Hehe :)

**Comment by kjac** [comment]
Oh this one was fixed a long time ago.
