### ISSUE TITLE
checkbox and dropdowns in Vorto?

### ISSUE THREAD

**Issue by bootnumlock** [kgiszewski/Archetype#347]
Running on UaaS so v.Latest of umbraco and also v.Latest of vorto and Archetype.

The combo of vorto and archetype looks to be a very nice marriage... however, if i create a datatype of checkbox or dropdown multiple... the values are not being noted in the raw JSON... HOWEVER, if i switch those datatypes to textfields... the data DOES indeed show up in the raw json... and it is THERE because the checkboxes and dropdowns display find in back office. Any thoughts???

**Comment by kgiszewski** [comment]
@bootnumlock, was this related to the thing we talked about the other day? i.e. can I close this?

**Comment by kjac** [comment]
I'm not sure I even understand this... 😟 @bootnumlock is this still an issue?

**Comment by kgiszewski** [comment]
@bootnumlock please let us know if this is still a thing. Closing for now.
