### ISSUE TITLE
Add option loads in first fieldset by default?

### ISSUE THREAD

**Issue by joseph-earnshaw** [kgiszewski/Archetype#352]
Hi, running version 1.12.3.

We seem to be having an issue where having the 'add' option is pre-selecting the first fieldset and populating when clicking add.

As an example for a 'mega menu': we have two archetypes, one for menu section (containing a link, and a property for the 2nd archetype) . This second archetype is set to start with the add button, and has 2 fieldsets (first a content picker, second for an image).

What we would expect on adding a menu item is an add button, which when clicked would display a droplist to state which fieldset to add. Instead it loads the content picker fieldset immediately, and presents no option for the second.

Anyone else seeing this issue?

**Comment by kjac** [comment]
@joseph-earnshaw I'm pretty sure the "add"-button now spawns the "select fieldset type" dialog, so I'm closing this issue. Please reopen it if I'm mistaken.
