### ISSUE TITLE
Allow Dragging of Fieldsets Between Nesting Barriers

### ISSUE THREAD

**Issue by Nicholas-Westby** [kgiszewski/Archetype#355]
Suppose I have an Archetype configured so each fieldset is a "widget" (e.g., rich text, image, etc.). Some of those widgets are containers (i.e., they can contain widgets). An example would be a "2 Column" widget that has two properties, each of the same data type as the Archetype widgets (i.e., a nested Archetype).

Would be super useful if those nested widgets could be dragged from inside the grid to outside the grid (i.e., to be siblings of the grid widget), or if the sibling widgets of the grid could be dragged inside of the grid. I often find myself wanting to do this, as sometimes I want to change a layout (e.g., to add or remove columns).

Even better, it would be great if fieldsets that are part of different Archetype data types but that are identical otherwise (e.g., same properties with the same data types) were considered compatible. That way, if I have a "Widgets" data type (i.e., plural) and a "Widget" data type (i.e., singular), I could do this nested dragging the same way as an actual Archetype that has fieldsets with properties that are of the same type.

Let me know if this isn't clear and I can add some screenshots.

**Comment by kgiszewski** [comment]
Whoa, killer idea! In a different project I used `ui-sortable` to drag between two containers. This one is likely to only be implemented via a PR since I don't have a direct need for this feature.

- There would be a need to have something define what is 'compatible' between two or more fieldsets to avoid allowing the dragging of a fieldset into a non-compatible fieldset (i.e. has no config to support it).
- This would probably be opt-in functionality.
- It might all 'just work' if we allow the drag/drop of ui-sortable to 'dock' to another fieldset wrapper.

**Comment by Nicholas-Westby** [comment]
I'll see if I can get this done today. If not, I'll have to leave it to somebody else or tackle it another time. I'll let you know.

**Comment by Nicholas-Westby** [comment]
This is mostly done, but I'll have to resume another day. Just need to modify it so it will check the target list's config to ensure the fieldset being dropped matches the list of configured fieldsets. You can see the progress here (currently two commits): https://github.com/Nicholas-Westby/Archetype/commits/feature/355-nested-dragging

Here's what it looks like:

![dragging](https://cloud.githubusercontent.com/assets/5933222/14774030/21942e1e-0a66-11e6-9d08-86204f4e2a84.gif)

One thing I may also want to consider is allowing multiple fieldsets to be open at once so I can drag between sibling fieldsets (e.g., the "grid" and "wrapper" in the above example).

**Comment by Nicholas-Westby** [comment]
Pull request submitted: https://github.com/imulus/Archetype/pull/356

Some notes:

- I decided not to worry about dragging between sibling nested fieldsets for now (e.g., between "Grid" and "Wrapper" in the above image). For my use cases, the ancestor usually is a common place that fieldsets can be dropped
- The drop will only occur if the fieldset can be removed from the source Archetype and can be added to the target Archetype.
- The drop will only occur if the fieldset is being dropped onto an Archetype that has a configured fieldset that matches the dragged fieldset (matches by the alias/guid of the properties).
- As a nice bonus feature, you can now drag between Archetypes on entirely different properties (e.g., between "Main Content" and "Bottom Content" in the above image).
- I had to ensure the drag icon is always shown, even when there is only one fieldset (made sense when dragging was restricted to one list, but makes less sense now).

Any chance this will make it in the upcoming version of Archetype? :-)

**Comment by kgiszewski** [comment]
I'm going to leave comments on the PR itself...

**Comment by kjac** [comment]
@Nicholas-Westby I belive this issue resolved?

**Comment by Nicholas-Westby** [comment]
Correct. I'll close.

**Comment by kjac** [comment]
👍
