### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kgiszewski** [kgiszewski/Archetype#361]
@kjac and @Nicholas-Westby If you would please add some documentation to this repo: https://github.com/kgiszewski/ArchetypeManual regarding your new awesome features. It would really help the assimilation of your new features.

**Comment by Nicholas-Westby** [comment]
Will do. I'll try to get to this next week.

**Comment by Nicholas-Westby** [comment]
Pull request here: https://github.com/kgiszewski/ArchetypeManual/pull/3
