### ISSUE TITLE
Unable to modify Archetype datatype, due to wrong reference to /Umbraco/App_Plugins/Archetype/js/archetype.js

### ISSUE THREAD

**Issue by joelbhansen** [kgiszewski/Archetype#370]
The reference should point to /App_Plugins/Archetype/js/archetype.js instead.

See https://github.com/imulus/Archetype/blob/master/app/Umbraco/Umbraco.Archetype/PropertyEditors/ArcheTypePropertyEditor.cs#L22

This bug was experienced with Umbraco 7.2.1

**Comment by kgiszewski** [comment]
Looks like we changed this about a year ago. It could be incompatible with your core version of Umbraco. 
See: https://github.com/imulus/Archetype/blame/master/app/Umbraco/Umbraco.Archetype/PropertyEditors/ArcheTypePropertyEditor.cs#L22

Suggestion would be to upgrade the core if possible, or run a custom build of Archetype to suit your needs. I know that might seem like a lot of work but it's probably the best way to handle legacy versions.

You could also try using a former version of Archetype (v1.12.0 or prior) as this change was tagged here with v1.12.1: https://github.com/imulus/Archetype/commit/43a72ed5e58cb4ae4e938bcdb524360948ba3bc1

**Comment by kjac** [comment]
@joelbhansen I hope you got your problem solved? Although we do our best to support older versions of Umbraco, 7.2.x is just a bit too old to keep supporting.
