### ISSUE TITLE
Cannot drag'n'drop sort fieldsets when there are just two

### ISSUE THREAD

**Issue by DanDiplo** [kgiszewski/Archetype#372]
Using latest 1.13.1 I created an Archetype and set `Max Fieldsets` to 2. I then found I couldn't use drag'n'drop sorting to order them - the order would always "snap" back to the original order. This was using latest Chrome 51.0.2704.103. If I set the `Max Fieldsets` value to 3 (or more) than sorting would work as expected.

**Comment by kgiszewski** [comment]
Thanks Dan, I'll have to look at this when I get a chance.

**Comment by benbracedigital** [comment]
Is there any update on this please? I client is complaining about it so would like to get it fixed for them

**Comment by karltynan** [comment]
I am also seeing this with 1.13.1 on Umbraco 7.5.2 - setting `Max Fieldsets` to 4 and having 4 items means I cannot drag and drop. Anything less or increasing the max by 1 would allow dragging again.

**Comment by kgiszewski** [comment]
Sorry no update on this at this time.

**Comment by Nicholas-Westby** [comment]
Interesting. Somebody is having an issue with max fieldsets set to 2, and another person is having an issue with max fieldsets set to 4. Maybe it's an issue with max fieldsets set to an even number. If I can reproduce the issue (haven't tried yet), I'll try to find some time this weekend to look into it.

Any chance one of you can paste the JSON for an example Archetype that demonstrates the problem? You can find the JSON under "Developer Options" (or whatever that button is called) for the Archetype.

**Comment by benbracedigital** [comment]
To add to that, my issue is with a max of 3!

**Comment by Nicholas-Westby** [comment]
Well there goes to the even max fieldsets theory. Haha.

**Comment by karltynan** [comment]
https://gist.github.com/karltynan/16898cae7b40614368587ef5add36695

**Comment by Nicholas-Westby** [comment]
By the way, are there any JavaScript errors in the browser console when dragging?

**Comment by karltynan** [comment]
No console errors.

**Comment by Nicholas-Westby** [comment]
Fix here: https://github.com/kgiszewski/Archetype/pull/378

Basically, when the Archetype contained the max fieldsets, the drag/drop operation would check if you had reached the max under the assumption that you were adding the fieldset to the Archetype (as would be the case if you were dragging the fieldset to another Archetype). This pull request adds a check so that if you are dropping the fieldset on the same Archetype it came from, the max fieldset check will be bypassed.

**Comment by kgiszewski** [comment]
Thanks for the PR Nicholas. I'll try to get it reviewed and released as soon as I can.

**Comment by kjac** [comment]
This is fixed by #378
