### ISSUE TITLE
Image Previews of Fieldsets

### ISSUE THREAD

**Issue by Nicholas-Westby** [kgiszewski/Archetype#374]
When a content editor adds an Archetype fieldset to a property, this is the selection dialog they see:

![add](https://cloud.githubusercontent.com/assets/5933222/17159950/242340a0-5356-11e6-9254-436e7a1e6006.png)

They have no idea that a "Link Sidebar Callouts" looks like this:

![links](https://cloud.githubusercontent.com/assets/5933222/17159986/68b7dc62-5356-11e6-802f-f449b57306cb.png)

Would be really useful if there were a "See Example" link next to that "Link Sidebar Callout" that, when clicked, showed the above screenshot.

So, the request is to be able to associate each Archetype fieldset with an image so content editors can have a better idea of what it looks like when they are constructing pages. I'd recommend presenting it as a link rather than displaying it inline, as displaying it inline would look a bit weird (assuming some of the screenshots would be very large).

It might looks something like this:

![see-example](https://cloud.githubusercontent.com/assets/5933222/17160064/f7953970-5356-11e6-99e7-70fff7d7c349.png)

Clicking that could just open the image in a new window, or could open it in a lightbox.

**Comment by kjac** [comment]
@Nicholas-Westby I like this idea a lot. It shouldn't be too hard to do, if we can make do with configuring relative paths on the server for each applicable fieldset, so we don't have to muck about with uploading files on the config page.

**Comment by Nicholas-Westby** [comment]
@kjac Configuring a path works for me. If we go with the simple option of opening the image in a new window, I can probably submit a pull request in the next few weeks (unless you want to tackle it before then).

**Comment by kjac** [comment]
@Nicholas-Westby I'll come up with something this weekend and run it past you.

**Comment by kjac** [comment]
@Nicholas-Westby how about something like this?

![archetype fieldset preview](https://user-images.githubusercontent.com/7405322/26990604-7755d3ae-4d57-11e7-8228-da55ba0b6ab5.gif)

**Comment by Nicholas-Westby** [comment]
That looks fantastic! Might be somewhat problematic for widgets that are wide (I'm assuming that's doing `max-width: 100%;`), but beyond that minor nitpick this looks like a huge improvement for usability when using Archetype for widgets.

One idea for improving the ability to view wide images would be to have a link in the image view that says "(open in new window)".

**Comment by kjac** [comment]
@Nicholas-Westby I've added a zoom icon when hovering the image, and wrapped the image in a link that opens in a new window. 

Looks something like this:

![archetype fieldset preview 2](https://user-images.githubusercontent.com/7405322/27000769-9aa55b1a-4db9-11e7-9383-436859797ff2.gif)

**Comment by kjac** [comment]
Fixed in v1.14.1
