### ISSUE TITLE
Min Fieldsets feature request

### ISSUE THREAD

**Issue by DanDiplo** [kgiszewski/Archetype#376]
It's really cool you can set a `Max Fieldsets` value, but it would also be useful if you could set a `Min Fieldsets` value, too. For instance, I often use Archetype for feature boxes on the homepage where the design dictates there should be (say) exactly three.

Even cooler would be the feature to be able to set a "multiplier" so you would always have to create _exactly_ `n * x` fieldsets.  For instance, if the multiplier is set to 3 then the validation would ensure there must be 3, 6, 9, 12 etc. fieldsets. This is useful for responsive designs where there is a column width.

Just something to think about for the next release if you ever are stuck for ideas :)

**Comment by Nicholas-Westby** [comment]
Seems like this is more or less a duplicate of: https://github.com/kgiszewski/Archetype/issues/249

The part that isn't a duplicate is the "multiplier" request.

**Comment by kjac** [comment]
Added in v1.15.1
