### ISSUE TITLE
Label Template not working for UrlPicker

### ISSUE THREAD

**Issue by gordonsaxby** [kgiszewski/Archetype#383]
Umbraco 7.5.6, Archetype 1.13.1, UrlPicker 0.16.1

I have created an Archetype with a UrlPicker and a Media Picker, with a Label Template of {{link}}. However, the label template does not work and I just get [Object Object].

This has worked on previous projects, albeit on previous versions of Umbraco / Archetype. E.g. it works with Umbraco 7.4.2, Archetype 1.12.4, UrlPicker 0.14.1

**Comment by kjac** [comment]
Hi @gordonsaxby,

You might try using the [Multi Url Picker](https://our.umbraco.org/projects/backoffice-extensions/multi-url-picker/) instead, it works really well with label templates.

**Comment by ELMDesign** [comment]
@kjac 

I cannot find any documentation anywhere on accessing the Multi Url Picker data for a label template.

If I reference the {{propertyAlias}} pattern as in the regular Url Picker I still get the [object Object] error
 I've tried {{meta.title}} {{name}} {{title}} and even concat with with the propertyalias and nothing works
Can you advise or share a link?

**Comment by kjac** [comment]
@ELMDesign it's been a while since I used this feature myself, but {{propertyAlias}} should work - or used to work, anyway. [This piece of code](https://github.com/kgiszewski/Archetype/blob/abf6917b1cfb908dd4ce520beacee57638d3049c/app/services/archetypeLabelService.js#L34) handles the Multi Url Picker.

**Comment by kjac** [comment]
The label template works latest version (2.0.1) of Multi Url Picker (tested on Umbraco 7.6 with the latest Archetype build).

![image](https://user-images.githubusercontent.com/7405322/26917303-0c427d3a-4c2e-11e7-8e82-5e7a590a926c.png)

**Comment by kjac** [comment]
Fixed in v1.14.1
