### ISSUE TITLE
Saving without publishing potentially causes invalid published data

### ISSUE THREAD

**Issue by kjac** [kgiszewski/Archetype#385]
Being able to save an invalid Archetype as draft (#151, fixed in #311) is nice, but with the various performance fixes and subsequent lazy loading of fieldsets, this feature enables the editors to publish invalid data.

When the Archetype is saved with invalid data in a fieldset, it reloads the editor and all validation state is reset (the fieldset is collapsed). Thus it has no idea that the fieldset is invalid, and the editors can hit publish without being prompted to correct the invalid data.

It's a catch 22, given the current validation handling. We're forced to choose between the "save as draft" feature and having valid published data. I'm going to choose the latter, so I'll remove the fix introduced in #311 - at least for the time being. Perhaps we can revisit this another time, if the demand for "save as draft" grows.

**Comment by kgiszewski** [comment]
I'm thinking the core has to provide some sort of way to help us determine these things.

I realize the core team doesn't really like nested data types, so I'm not terribly optimistic :)
