### ISSUE TITLE
Dollar Signs (Unintentionally?) Collapsing in Pairs?

### ISSUE THREAD

**Issue by Nicholas-Westby** [kgiszewski/Archetype#387]
Somebody editing the content for the main navigation (built with Archetype) on a site we're building noticed this:

![dollars](https://cloud.githubusercontent.com/assets/5933222/23033071/9f3a503c-f42b-11e6-9f8c-01e54bba111f.png)

It seems that the Archetype header is combining pairs of dollar signs. So, if you have 2, it becomes 1. If you have 3, it becomes 2. If you have 4, it becomes 2.

Here's how the Archetype fieldset is configured:

![configuration](https://cloud.githubusercontent.com/assets/5933222/23033278/4e899f20-f42c-11e6-8a6d-63c828c2ea91.png)

My guess is that this is some obscure Archetype feature misbehaving or that maybe this is related to however you are replacing strings with Angular (i.e., perhaps Angular combines dollar signs).

Archetype 1.13.1.

**Comment by kgiszewski** [comment]
That's not intentional and strange :)

Does escaping it help at all?

**Comment by Nicholas-Westby** [comment]
Not entirely sure what you mean, but I gave this a try and it didn't help (other than the backslash separating the dollar signs, and so preventing the combining):

![escaped](https://cloud.githubusercontent.com/assets/5933222/23034270/272e850e-f430-11e6-8ecd-a598ed164a4f.png)

**Comment by kgiszewski** [comment]
Yep that's what I meant and it's a head-scratcher.

**Comment by kgiszewski** [comment]
Could you add quotes around then who expression (sorry I can't think of the reason)?

**Comment by kjac** [comment]
Ah glorious JS. It's just one of them things... dollar signs have a special meaning in string replacement. And when we calculate the fieldset template, we do indeed use string replacement (and rightfully so). [This line](https://github.com/kgiszewski/Archetype/blob/abf6917b1cfb908dd4ce520beacee57638d3049c/app/services/archetypeLabelService.js#L273) is the culprit.

But.. it's "just how JS works", I'm afraid. Try this in your Chrome JS console: 

`"i am a string".replace("am", "$$$$$")`

You'd expect the result to be `"i $$$$$ a string"`, but noooo... the result is `"i $$$ a string"`

![image](https://cloud.githubusercontent.com/assets/7405322/23037461/b3b2dcfe-f486-11e6-98b6-d29860ea33e4.png)

**Comment by Nicholas-Westby** [comment]
Ha, awesome. Never knew that. According to this, you are correct: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

![replacement](https://cloud.githubusercontent.com/assets/5933222/23037572/b33af0e0-f43b-11e6-9c96-47405cd2968f.png)

Maybe we should first replace all dollar signs with double dollar signs (effectively escaping them) before calling replace?

**Comment by kjac** [comment]
@Nicholas-Westby that was my first thought too... but I'm afraid it might mess up someone's fancy angular label template, or cause other equally unintended problems.

**Comment by kgiszewski** [comment]
@Nicholas-Westby this might be more trouble that it's worth to fix. Would using `####-#####` suit your needs?

Curious if adding the extra `$`'s are sufficient as well. 

And if you've never seen this video below, you're missing out on life.

https://www.destroyallsoftware.com/talks/wat

**Comment by kjac** [comment]
@Nicholas-Westby if you really must, you can create your own label template that escapes the dollar signs. A bit annoying, yes, but... I do agree with @kgiszewski, fixing it might lead to a lot of other issues.

**Comment by Nicholas-Westby** [comment]
I'll probably just ignore the issue. Only happens one a small part of the CMS (back office cosmetic is not on my priority list).

However, I'd be open to submitting a pull request if you were open to it. In my case, it would not be acceptable to add extra dollar signs. And they do need to be dollar signs (they are shown in a navigation menu to represent price ranges), so can't use the pound symbol.

I'm thinking that anybody actually intending to use this would be very unlikely. And even if there are, I'd consider it akin to this: https://xkcd.com/1172/

My perspective is that "what it says it will do on the tin" does not match what it does (i.e., the dollar sign functionality seems like an unintentional side effect rather than something intended and useful). My guess is it causes problems much more often than it solves issues.

I'm OK with whatever you would prefer, but this seems to me to be clearly a bug that ought to be fixed. The fix would be to simply double every dollar sign before calling replace.

And if anybody actually is relying on the dollar sign special behavior:

![watman](https://cloud.githubusercontent.com/assets/5933222/23199406/083a14f4-f883-11e6-8867-327c370d38ac.jpg)

(Sad Watman)

**Comment by kjac** [comment]
Hey @Nicholas-Westby,

I'm mostly concerned with people using stuff like `$scope` and `$filter` in their label templates... not people relying on this (awesome) JS feature.

**Comment by Nicholas-Westby** [comment]
@kjac Not sure I follow. I don't see how escaping dollar signs would affect `$scope` or `$filter` if it were done just before this line:

![replace](https://cloud.githubusercontent.com/assets/5933222/23220220/1292970c-f8d6-11e6-8d19-a03296557c9d.png)

Do you mind going into a bit more detail?

To clarify, I'm thinking of simply doubling dollar signs in `templateLabelValue` to prevent the issue.

**Comment by kjac** [comment]
This is fixed by #406 - the issue will be closed when the next release is ready.

**Comment by kjac** [comment]
Fixed in v1.14.1
