### ISSUE TITLE
Tiny feature request : column and row numbers

### ISSUE THREAD

**Issue by podulator** [kgiszewski/Archetype#388]
Hi, 

On big pages it has been really useful for our editors to have row and column numbers available as everything contracts on save / publish. Too small to pull request I think, but hopefully useful?

https://github.com/kgiszewski/Archetype/blob/abf6917b1cfb908dd4ce520beacee57638d3049c/app/services/archetypeLabelService.js#L179

            if (template.length < 1)
                return fieldsetConfig.label;

just becomes 

            if (template.length < 1)
                return fieldsetConfig.label + " " + (1 + fieldsetIndex);

**Comment by Nicholas-Westby** [comment]
I wonder if this would be a good use case for a fieldset label function (or whatever it's called). That is, you can call custom functions that return whatever you want to be displayed in the fieldset label.

On the other hand, I'm not sure if fieldset index is a parameter that gets sent as input to those functions, so the core Archetype code might need to be modified to facilitate that.

**Comment by kjac** [comment]
@podulator I agree with @Nicholas-Westby - it'd be a good case for a custom function to handle the fieldset label. The index of the fieldset is currently not added as a parameter to these functions, but that could easily be mended, and could have additional uses on its own (e.g. odd/even using %2).

However, perhaps it'd be better to address the actual issue, namely fieldsets automatically collapsing on save/publish?

**Comment by podulator** [comment]
Both enhancements sound very very useful, but @kjac , I think having a column / row Id or name is stil useful for working on big pages, as the page performance seems better without every row being loaded and expanded :)

**Comment by kjac** [comment]
@podulator as I understood your initial comment, the numbers were supposed to mend the issue with automatic collapsing on save/publish?

**Comment by podulator** [comment]
Well, i was a quick work around for 2 issues really, one is for sure the expand / contract on publish situation meaning you lose yr place while yr working. The other one is that on big pages it's much quicker jumping to the row you know you want if you're coming back to make a quick change on something that you've been working on and know which row contains the pertinent content, you can go straight to it...
cheers

**Comment by kjac** [comment]
@podulator my main concern with this is that all template-less fieldsets would get this numbering added to their labels, regardless of type and any templated fieldsets in between.

Say you have an Archetype with three different types of fieldsets. Two of them have no label template and are simply labeled "Fieldset 1" and "Fieldset 2", while the last one is templated using the `title` property contained within. The result would look something like this:

- Fieldset 1 (1)
- Fieldset 1 (2)
- Type yer title here
- Fieldset 2 (4)
- Another fieldset in the wall
- Fieldset 2 (6)
- Fieldset 2 (7)
- Fieldset 1 (8)

I'm afraid the editors would get rather confused by this.

**Comment by kjac** [comment]
I'm going to close this due to lack of activity. Feel free to reopen if there is additional input to be considered.
