### ISSUE TITLE
Files are still disappearing in image cropper and file upload

### ISSUE THREAD

**Issue by kjac** [kgiszewski/Archetype#389]
The fix for #384 needs to be extended a bit. It works for regularly named files, but as soon as you start adding special chars like `@` to the file names, it doesn't work any longer.

I'll have to look into the sanitizing of file names that's going on on the Umbraco side of things, and either piggybag on it or replicate it within Archetype.

**Comment by mortenholmgaard** [comment]
And it does not work with spaces either.

**Comment by DanDiplo** [comment]
Yes, probably the biggest issue is that it fails silently if the filename has a space in it, which is quite common for image filenames on Windows.

**Comment by kjac** [comment]
#400 fixes this issue for Umbraco versions below 7.6.

**Comment by kjac** [comment]
Fixed in v1.14.1
