### ISSUE TITLE
Multi-Url Picker inside Archetype not resolved on Umbraco Cloud

### ISSUE THREAD

**Issue by bjarnef** [kgiszewski/Archetype#391]
I have a Multi-URL picker inside Archetype. When deploying from local to live environment it does deploy the picked links, but it doesn't resolve the links (it reference to the local ids not the node ids on live environment). https://our.umbraco.org/projects/backoffice-extensions/multi-url-picker/

I am pretty sure it did work previously, but I am not sure if an Umbraco upgrade or courier might have changed this.

When clicking edit on these links in live environment after deploy, it therefore returns the following error.
![clipboard_1](https://cloud.githubusercontent.com/assets/2919859/24495993/50f82a98-1537-11e7-9111-596c655c0929.png)

I am not sure if this is an issue with Arcehtype or the Multi-Url Picker.

**Comment by kjac** [comment]
@bjarnef a new version of the Multi URL Picker was just released to address a similar problem. Could you check if updating it solves this issue?

**Comment by bjarnef** [comment]
@kjac yes, the issue was also happening when not inside Archetype and just as a standalone property. I have noticed the new v2 og multi-url which also updates the ui styles, which is consistent with Umbraco 7.6 and newer version. This project is in Umbraco 7.5.. not sure if the v2 fix the issues on Umbraco 7.6 cloud and with Deploy.
