### ISSUE TITLE
Data Type Configuration Screen Slow With Many Fieldsets

### ISSUE THREAD

**Issue by Nicholas-Westby** [kgiszewski/Archetype#393]
I have an Archetype with 62 widgets/fieldsets:

![archetype-widgets](https://cloud.githubusercontent.com/assets/5933222/24877809/85d0d5a6-1de5-11e7-9506-3884e7a872e0.png)

When creating widgets in the content section, it's nice and zippy. When loading this screen (the data type configuration for my Archetype), it takes about 18 seconds to load, and typing has a lag.

I'm thinking this speed issue can be solved in the same way the speed issue in the content section was solved (i.e., use `ng-if` to avoid processing collapsed fieldsets).

Happy to submit a pull request if you like.

**Comment by kjac** [comment]
Hey! Not a bad idea. I'm rebooting the project for a new release, in order to address some of the issues related to the recent Umbraco releases. This makes sense to include as well. I'll get back to you ☺️

**Comment by kjac** [comment]
Fixed in the next release - we'll keep the issue open until the release is out.

**Comment by kjac** [comment]
Fixed in v1.14.1
