### ISSUE TITLE
Problem with upper-case filenames when using upload type

### ISSUE THREAD

**Issue by timmather** [kgiszewski/Archetype#394]
When using an "upload" data type within an Archetype control if the file name has any upper-case characters in the it will not upload. There don't seem to be any entries logged in the log file?

Umbraco 7.5.11
Archetype 1.13.2

**Comment by kjac** [comment]
There's a general problem with image names that contains anything but lowercase letters. I'll be looking into this soon.

**Comment by kjac** [comment]
#400 fixes this issue for Umbraco versions below 7.6.

**Comment by kjac** [comment]
Fixed in v1.14.1
