### ISSUE TITLE
Archetype as Mandatory property is not being honored

### ISSUE THREAD

**Issue by wkallhof** [kgiszewski/Archetype#395]
After creating a new Archetype property reference on a Document Type and setting that field as Mandatory, when creating content, I am able to save the content without entering any Archetype data (it isn't mandatory). I suspect that Umbraco sees that the property has value (Archetype has it's JSON data being stored as the property value).

**Expected Results**
I can set an Archetype property on my Document Type as mandatory and it wont let me save the page until I enter some value for that Archetype property

**Action Results**
I am able to save a page without entering any Archetype property value, even thought it is configured as mandatory.

**Comment by kjac** [comment]
I guess the only solution to this is to introduce an option to specify a minimum required number of fieldsets. I'll have a look at it.

**Comment by kjac** [comment]
Fixed in v1.14.1
