### ISSUE TITLE
RJP.Mulit Url Picker Inside ArcheType showing Error in Umbraco 7.6

### ISSUE THREAD

**Issue by sumeshkp18** [kgiszewski/Archetype#398]
I have created [Multi Url Picker](https://our.umbraco.org/projects/backoffice-extensions/multi-url-picker/) inside [Archetype](https://our.umbraco.org/projects/backoffice-extensions/archetype/). When I add an item in archetype from content, the property the Link field shows a message
`You need to add at least {{model.config.minNumberOfItems}} items  You can only have {{model.config.maxNumberOfItems}} items selected`

If I try to add an item in the URL Picker, The tab area will disappear. 

If I save the archetype without adding content URL picker and try to add URL in the URL picker the message will not show again.

Please take a look into this issue.
Here is the screencast of issue - https://goo.gl/DSQW8M

I'm not sure this error belongs to RJP.Mulit Url Picker OR ArcheType
![RJP.Mulit Url Picker Inside ArcheType showing Error in Umbraco 7.6](https://cloud.githubusercontent.com/assets/10336763/26273016/7c992a78-3d44-11e7-8698-a34c921cc33a.jpg)

**Comment by sumeshkp18** [comment]
@rasmusjp @kgiszewski

**Comment by Nicholas-Westby** [comment]
Looks like you are one version behind on Archetype (latest is 1.13.2, and you seem to have 1.13.1). Maybe see if upgrading helps. You can get the latest on NuGet; not sure why our.umbraco.org is showing the older version.

Supposing this is still a bug, my guess is this will take some time to get fixed. In the meantime, have you considered using Archetype instead of Multi Url Picker? Take a look at this article to replicate with Multi Url Picker does using Archetype instead: https://code101.net/links-in-umbraco-are-broken-but-alternatives-exist-1fe89aae2093

**Comment by vmburd** [comment]
I just encountered this problem with the Multi Url Picker outside of Archetype on Umbraco 7.6.1. When I checked the javascript console it showed errors in DependencyHandler so I bumped the ClientDependency number in the config file and recycled the App Pool.  Now it works fine.  I haven't use the picker within Archetype so can't comment on whether this will solve the issue for @sumeshkp18

**Comment by sumeshkp18** [comment]
Hi @Nicholas-Westby ,
Yes, You are right. 
I have upgraded the Archetype version, But still getting the same error. 
Anyway thanks for the alternate option suggestion.

**Comment by rasmusjp** [comment]
Hi @sumeshkp18 
I've just released a new version of the Multi Url Picker which should resolve this problem.

It looks like archetype isn't calling the server side methods on create, which I've workaround in the latest version of the Multi Url Picker.

**Comment by kgiszewski** [comment]
@rasmusjp Thank you!

**Comment by sumeshkp18** [comment]
Thank you very much @rasmusjp . Latest version solved my issue 👍
