### ISSUE TITLE
Fail to convert the value when GetValue<int>() ?

### ISSUE THREAD

**Issue by samsam321** [kgiszewski/Archetype#413]
I am new in umbraco and Archetype, I am not sure this is a bug or not. I am sorry for that if it is not a bug. 

In my case,  I am learning the umbraco and following [Paul Seal Video](http://www.codeshare.co.uk/videos/how-to-build-a-site-with-umbraco-part-7-introduction-to-archetype/) 
, 

![image](https://user-images.githubusercontent.com/5652498/27323189-3f2dc7d2-55d3-11e7-95a9-0d15346e02de.png)

when I try to get the image id ( mediapicker) by GetValue<int>, but it is fail.

Then I digging into the Archetype source, find out the convert fail 

![image](https://user-images.githubusercontent.com/5652498/27323009-9dfbf226-55d2-11e7-92f2-ca0f7d6ef949.png)

But as I said I am new comer, I am not fully understand is it anything wrong with the convertor

![image](https://user-images.githubusercontent.com/5652498/27323415-11ad23ec-55d4-11e7-8352-c1d328f68aa6.png)

From the debugger, there are 35 convertr but with no MediaPicker2, is that the problem ? 

Is there anyone can answer that ? thanks a lot.

Ref:
Umbraco v7.6.3
Archetype v1.14.1

**Comment by samsam321** [comment]
Oh, I found the problem is here ,

![image](https://user-images.githubusercontent.com/5652498/27325219-4be90bba-55da-11e7-84e8-36665b6b34de.png)

value3 is the imageId (mediaId) but it is not a integer , so the converter will be fail.

If I getValue<object>("image") , then I can get the image object, but first question is this a proper way to get the image ? if I get the object first, then get the id by the object. second question is how can I get the imageId by object ?


the function only try to convert the value2 
![image](https://user-images.githubusercontent.com/5652498/27325438-081c2e34-55db-11e7-876c-7f1dc5515575.png)

is it need to try to convert value3 also , is it here to cause the problem ? Hope the author can help to answer it . Thanks a lot

**Comment by kjac** [comment]
Hi @samsam321,

That's some impressive debugging you've been doing :)

As of Umbraco 7.6, the built-in pickers (content picker, media picker etc) resolve to `IPublishedContent` instead of `int`. It's a really nice change but it is causing a lot of headaches around the world.

Try using `var mediaItem = fieldset.GetValue<IPublishedContent>("image");` and `var linkedToPage = fieldset.GetValue<IPublishedContent>("page");` instead and see if that works?

**Comment by samsam321** [comment]
Hi @kjac,

Thanks for reply. :)

I have tried your method and it is working. Thank you very much . ^^ At least I have a work around for that .

**Comment by bhagirathpancholisa** [comment]
hello @kjac @samsam321 
thanks for solution,i tried your solution and at debugging stag i get value on imageurl but still linkurl is getting null. can u solve this? below is my code

```
 var mediaItem = fieldset.GetValue<IPublishedContent>("image");
                string imageUrl = mediaItem.Url;

                var linkTopage = fieldset.GetValue<IPublishedContent>("page");
                string linkUrl = linkTopage.Url;


 model.Add(new FeaturedItem(fieldset.GetValue<string>("name"), fieldset.GetValue<string>("category"), imageUrl, linkUrl));
```
![1](https://user-images.githubusercontent.com/31622354/32260089-970a8fc2-beeb-11e7-90d7-2815a40a318f.PNG)
![2](https://user-images.githubusercontent.com/31622354/32260090-97754240-beeb-11e7-8181-ca4da100343e.PNG)
