### ISSUE TITLE
Missing Placeholder Translation Text for Icon Filter

### ISSUE THREAD

**Issue by Nicholas-Westby** [kgiszewski/Archetype#415]
For each fieldset in Archetype, you can choose an icon:

![archetype-icon-picker](https://user-images.githubusercontent.com/5933222/28139750-4412b4ae-670a-11e7-8f57-068956140da9.png)

Notice that the placeholder doesn't seem to be translated. However, in Umbraco's built-in icon picker for document types, the placeholder is translated correctly:

![doctype-icon-picker](https://user-images.githubusercontent.com/5933222/28139779-627f8034-670a-11e7-955f-a0c3de3b040c.png)

I can think of two possible reasons off the top of my head for why the Archetype variation is failing:

* Perhaps the AngularJS directive responsible for translating this placeholder changed.
* Perhaps this translation was part of the Umbraco core, and the key for it was changed in a recent version of Umbraco.

Umbraco 7.6.4 (latest version) and Archetype 1.14.1 (latest version).

**Comment by kgiszewski** [comment]
Yea weird. We use the stock icon picker in Umb if I recall. Wonder if it's a scoping issue?

**Comment by Nicholas-Westby** [comment]
I'm not sure if it's entirely the same one. Maybe you use the stock icon display, but you customize the filter input field? Note Archetype doesn't have the header ("Select icon") and the scrollbar starts at a different spot (next to the color drop down rather than next to the filter text field).

**Comment by Nicholas-Westby** [comment]
By the way, I checked recent (but not latest) versions of Archetype and Umbraco, and here's what they look like. Archetype:

![old-archetype](https://user-images.githubusercontent.com/5933222/28140799-a884518c-670e-11e7-8950-75275d301d5e.png)

Doctype icon picker:

![old-doctype](https://user-images.githubusercontent.com/5933222/28140802-aed9b662-670e-11e7-8822-e848eba408a5.png)

Note the placeholder text is different. I imagine this means that text field is different between the two of them.

**Comment by kgiszewski** [comment]
TBH, I don't even remember when the icon picker was integrated into Archetype. I know Archetype is built against an old Core DLL (7.1.2) but I don't think that'll effect the assets\translations.

**Comment by kgiszewski** [comment]
https://github.com/kgiszewski/Archetype/blob/master/app/controllers/config.controller.js#L29-L35

Yea we're just calling the dialog it seems.

**Comment by Nicholas-Westby** [comment]
Interesting. It seems like the Umbraco core opens the icon picker in a slightly different way. Here's the JavaScript that sets a view model object: https://github.com/umbraco/Umbraco-CMS/blob/da4be3be6559aac1a93a87fc3074532bcb422999/src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditorheader.directive.js#L211

And here's the AngularJS directive that is making use of that view model object: https://github.com/umbraco/Umbraco-CMS/blob/da4be3be6559aac1a93a87fc3074532bcb422999/src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editor-header.html#L81

I'm not sure if `<umb-overlay>` was added in a newer version of Umbraco, so I'm not sure if using that approach would be workable for Archetype (since it has a minimum required version of 7.2.x, IIRC). Might work though.

I'll submit a bug report with the Umbraco core issue tracker.

**Comment by Nicholas-Westby** [comment]
Issue reported to the core Umbraco issue tracker: http://issues.umbraco.org/issue/U4-10152

**Comment by Nicholas-Westby** [comment]
This has been fixed in the latest core version of Umbraco (7.6.6):

![new-icon-picker](https://user-images.githubusercontent.com/5933222/30333713-7cc7a6b6-9792-11e7-81fb-53567983d7ce.png)

Closing this issue.
