### ISSUE TITLE
Convert DataType Drop Down to Select2

### ISSUE THREAD

**Issue by Nicholas-Westby** [kgiszewski/Archetype#416]
When constructing the Archetype fieldsets by adding properties, there is a drop down that allows you to select the data type of each property. Can take a bit of time to scroll through the list when there are a lot of data types.

Rather than a plain drop down, I think it'd be much nicer to be able to type a portion of the data type name to see a filtered list to select from:

![select2-data-types](https://user-images.githubusercontent.com/5933222/28187082-3f370070-67d2-11e7-8ab8-ebd176448444.gif)

This is a relatively frivolous feature request, but can't hurt to ask :-)

**Comment by kjac** [comment]
@Nicholas-Westby correct me if I'm wrong, but wouldn't this require a thirdparty JS lib included?

**Comment by Nicholas-Westby** [comment]
@kjac That is correct, Select2 is a third party JavaScript library.

**Comment by kgiszewski** [comment]
Would prefer to avoid 3rd party stuffs if we can.

**Comment by kjac** [comment]
@kgiszewski thank you. I really do agree with that perspective - less maintenance and bug chasing that way. 

I think we should hold off on this for now, and reconsider if more people start reporting something similar. Is that ok with you, @Nicholas-Westby?

**Comment by Nicholas-Westby** [comment]
Totally understandable. I'll go ahead and close this issue.
