### ISSUE TITLE
ToPublishedContentSet Throws Exception for Orphaned Properties

### ISSUE THREAD

**Issue by Nicholas-Westby** [kgiszewski/Archetype#418]
You can read the detailed version here: https://github.com/leekelleher/umbraco-ditto/issues/221

In short, I created an Archetype fieldset, created some content based on that, then renamed a property. When I try to get at that content (I'm mapping it with Ditto), I get a null exception. The problem seems to start here: https://github.com/rhythmagency/rhythm.umbraco.ditto.archetype/blob/aeb9402dad2f39a8b506b7036b0ee068ed706432/src/Rhythm.Umbraco.Ditto.Archetype/Processors/DittoArchetypeAttribute.cs

That code is called `ToPublishedContentSet`. That in turn creates some Umbraco published property types, which in turn get run through property value converter. Something is null along the way, which causes a null exception.

I think it's because the saved JSON data still contains the old data, and Archetype tries to match that up with the Archetype fieldset definition, but there is a mismatch.

The ideal solution would be for Archetype to completely disregard any orphaned properties within a fieldset.

Latest version of Archetype (1.14.1), Umbraco (7.6.4), and Ditto (0.11.0).

**Comment by kjac** [comment]
Fixed. We'll keep the issue open until a new release is ready.

**Comment by kjac** [comment]
Fixed in v1.15.1
