### ISSUE TITLE
Label Templates Not Fully Resolving in Umbraco 7.4.3

### ISSUE THREAD

**Issue by Nicholas-Westby** [kgiszewski/Archetype#432]
Not entirely sure what's going on here, but I thought I'd make you aware of it:

![widgets](https://user-images.githubusercontent.com/5933222/30766256-9e0179b0-9fa8-11e7-8b23-15f9d57698d8.png)

You can see that parts of the label templates are showing up, but the dynamic portions are not (i.e., the parts I've circled should show the value of properties).

Some theories before I dig into this too much:

* Nested Archetypes may be throwing off the promises.
* This particular Umbraco version may be returning data in a different way than Archetype expects.

That's all that I can think of at the moment off the top of my head. Might have some time this weekend to dig into this.

FYI, the label templates all look something like this:

```
[Banner] {{labelIgnored}}
```

The "labelIgnored" is a plain text property.

Archetype 1.17.0. Umbraco 7.4.3. Upgraded Archetype with NuGet from 1.15.1. Cleared all server and client caches.

**Comment by Nicholas-Westby** [comment]
Here's what those look like after I downgrade to Archetype 1.15.1:

![downgraded-widgets](https://user-images.githubusercontent.com/5933222/30766495-5cb4c802-9faa-11e7-928b-5a242a39db94.png)

**Comment by Nicholas-Westby** [comment]
Another theory: I have multiple Archetype properties on this page. Could be that they are interfering with each other.

**Comment by kgiszewski** [comment]
Lemme know what you find out.

**Comment by Nicholas-Westby** [comment]
I think the problem started with this commit: https://github.com/kgiszewski/Archetype/commit/3a2190b232862d6e791145a9e99ad247bcd4eb31#diff-f9dc560ec686175ddc2f121b9206e18cR550

This was the old logic:

```js
var label = getNativeLabel(datatype, templateLabelValue, scope);
if(label) {
    templateLabelValue = label;
}
```

Essentially, if the there is a value returned from `getNativeLabel`, it would be used; otherwise, the `rawValue` (set a few lines above) would be used instead.

With the new code, the value from `getNativeLabel` is always used, even if it returns nothing.

I'll see if I can get a quick fix working (may be as simple as reverting a few lines to the old code) and submit a pull request.

**Comment by Nicholas-Westby** [comment]
Pull request here: https://github.com/kgiszewski/Archetype/pull/433

**Comment by DanDiplo** [comment]
Just to mention I'm seeing this in latest Umbraco 7.7.1 - after upgrading Archetype all label templates have disappeared. I applied Nicholas's fix and it worked, so gets a vote from me!

**Comment by kgiszewski** [comment]
@DanDiplo Thanks for the feedback and appreciate the support. I'm gonna close the issue as @Nicholas-Westby 's PR was merged this morning.

**Comment by kgiszewski** [comment]
@Nicholas-Westby @DanDiplo Published: https://www.nuget.org/packages/Archetype/1.17.1

May take a few minutes to index on Nuget.

**Comment by Nicholas-Westby** [comment]
Sweet! I'll give it a test once the NuGet index is up to date.

**Comment by DanDiplo** [comment]
Thanks, Kev, for your quick work - and Nicholas for your work.
