### ISSUE TITLE
Upgrade Check Ironically Fails to Run on Upgraded Archetype Installs

### ISSUE THREAD

**Issue by Nicholas-Westby** [kgiszewski/Archetype#435]
I had an older version of Archetype installed and I upgraded to the latest version, 1.17.1. I had remembered that you added an upgrade check and an option to disable it, so I went to the developer section, found a configured Archetype data type, and toggled the option so that I will no longer get an upgrade check.

Trouble is, I never got the upgrade check in the first place (I assume it pops up a notification when visiting a configured Archetype data type in the developer section). My theory is that because installs of Archetype that get upgraded don't get a new `Archetype.config.js` file, which I suspect is necessary for upgrade checks to work (because you'd need the GUID in that file for the upgrade check).

Once I toggled the upgrade check option, the `Archetype.config.js` file was created and it contained this:

```json
{
  "Id": "some-guid",
  "CheckForUpdates": false
}
```

FYI, I'm managing upgrade to Archetype on this install with NuGet.

BTW, you might consider adding a static variable or something so that the upgrade check runs less frequently. A coworker of mine expressed dismay at the fact that the notification popped up every time he visited an Archetype in the developer section.

**Comment by kgiszewski** [comment]
The `Archetype.config.js` file regenerates if it detects it's missing or corrupt. It's very possible that the boolean that represents the 'should i check?' is defaulting to false and skipping the file regeneration. I'd have to upgrade an old site to be sure.

Re: dismayed coworker...

1) Buy him an overly priced latte to cheer him up
2) Consider upgrading
3) Opt-out of the checker
4) Wait for the PR to be merged that I'm about to write with your suggestion

Thanks for the reporting.

**Comment by Nicholas-Westby** [comment]
> Opt-out of the checker

That was the solution I recommended :-)

> Wait for the PR to be merged that I'm about to write with your suggestion

Awesome!
