### ISSUE TITLE
Courier bundled in (again)

### ISSUE THREAD

**Issue by kgiszewski** [kgiszewski/Archetype#438]
@leekelleher,

I've been asked by Umb HQ if we can bundle in Courier into our main build. If I recall correctly when we did that it broke non-Courier installs.

If that may still be the case, the alternative might be to bundle it into Courier.Contrib. https://github.com/umbraco/Umbraco.Courier.Contrib

Lee, since you've contributed to both projects; I value your input.

The implied message from HQ is that Archetype could lose it's "Works on Umbraco Cloud" designation despite having a resolver.

![image](https://user-images.githubusercontent.com/4653907/31439571-a2b74d0c-ae5a-11e7-8aaf-3366d11f40ff.png)

- kg

**Comment by leekelleher** [comment]
@kgiszewski - yup, if it's included, then it will 100% break for non-Courier installs! **Definitely a no-go**!

IMHO [Umbraco.Courier.Contrib](https://github.com/umbraco/Umbraco.Courier.Contrib/) is the best place for it, I opened a ticket for this a while ago, https://github.com/umbraco/Umbraco.Courier.Contrib/issues/17

I guess it "just" needs someone to copy it over & refactor it to loosen any dependency on the Archetype binary reference.  (I guess everyone's expectation is on me, but it's _waaaay_ down on my todo list)

...and then there's also the [Umbraco.Deploy.Contrib](https://github.com/umbraco/Umbraco.Deploy.Contrib) too, (which I haven't written an Archetype resolver, _cough, I mean_ value-connector for).  I suspect this is where the **_losing the "Works on Umbraco Cloud" label_** thing is really coming from.

**Comment by leekelleher** [comment]
@kgiszewski - how did HQ ask you? Direct email or publicly via GitHub/Twitter?

**Comment by kgiszewski** [comment]
Via DM on Twitter. I promised to ask you ☺

And you should feel zero obligation to do any coding on this.

Cloud hasn't really been high priority and the ROI on this might be low right now for me.

We might just have to lose the designation for now.

Thanks for your input and time as always.

**Comment by kgiszewski** [comment]
Closing for now,we can re-open if needed later.
