### ISSUE TITLE
Firefox - Can't click any input fields

### ISSUE THREAD

**Issue by tomfulton** [kgiszewski/Archetype#61]
In Firefox, its impossible to click on any input fields in the Archetype Editor (or dropdowns, etc) or Prevalue Editor when sorting is enabled.

This looks to be because the copy of `angular-ui-sortable` in the [Umbraco Core](https://github.com/umbraco/Umbraco-CMS/commit/da2f3aefe6f487507f565bca6a7b4da7863dde51#commitcomment-5453911) that we're referencing, is calling `.disableSelection()`, which causes this known issue in Firefox.

This doesn't look to be an issue in the [angular-ui-sortable](https://github.com/angular-ui/ui-sortable) standalone directive, but it appears the copy in the core has been modified a bit.  Unfortunately, the copy in the core is minified, so it's difficult to see what's _really_ going on, though I think its only that one change.

I'm hoping we can find out from HQ about why that was added and if it can be removed, since it's deprecated anyway.  Couldn't seem to find any bugs with it removed.

As a VERY hacky workaround, I tried doing this, but it seems its happening on more than just `input` elements (`option`, who knows what else), so I'm not sure how well this really works or if we should just run it on a bunch of controls.

```
$timeout(function() {
    $('.archetypeEditor .controls input')
        .bind('mousedown.ui-disableSelection selectstart.ui-disableSelection', function(e) { 
            e.stopImmediatePropagation();
        }); 
}, 1000);
```

As another option, I was hoping we could just use the _real_ copy of `angular-ui-sortable`, but I don't think that's possible since it'll be using the same name as the core's copy.

Umbraco bug:  [U4-4281](http://issues.umbraco.org/issue/U4-4281)

**Comment by kjac** [comment]
Fixed... at some point :)
